### ISSUE TITLE
[Study] Feedbacks

### ISSUE THREAD

**Issue by srngch** [hhkim0729/vanilla-counter#1]
우선 파일 구조 깔끔한거 최고.. 아시는 부분도 있겠지만 저도 공부할 겸 세세하게 남겨봅니다. 제가 이유를 캐치하지 못 한부분이 있다면 커맨트 남겨주세요!

/src/js/index.js:8, 9
좀 더 명확한 변수명은 어떨까요? (ex: `counters` -> `countersLocalData`)
그럼 10, 11 라인의 삼항연산자 부분도 자연스러운 문장처럼 읽할 듯 합니다.

/src/js/index.js:19
이벤트 리스너에 연결된 모든 곳에서 `update()`가 실행되는데 update 안에서 매번 카운터의 인스턴스들를 새롭게 생성하는 이유가 궁금합니다.

/src/js/index.js:40
질문. 아직 안 쓰인 메소드인데 추후 어느 상황에서 쓰이게 되나요?

/src/js/index.js:58
render() 메소드 저도 고민 많이하다가 매 번 개별 카운터의 dom을 추가/수정/삭제하는 방법으로 짰는데, 리액트 같이 버츄얼돔이 없는 상황에서 매번 모든 카운터를 그려주면 비효율적일 같아요. 하지만 코드에서 잘 읽히고 관리하기 쉬운 장점이 있을 것 같습니다. 이 부분은 같이 얘기 나눠보고 싶어요!

/src/js/index.js::101
자잘한 거지만... 반복되는  `e.target.classList`를 콜백 함수 초반 부분에서 const에 할당 가능.

/src/js/index.js::102
더 이상 필요하지 않은 경우 return으로 함수 끝내버리는거 넘 좋아요.

/src/js/index.js::134
html에서 script 태그가 맨 아래 있어서 window.onload가 없어도 동일하게 작동.
저는 js 파일 연결을 head 태그 안에 defer로 추가했는데 자세한건 링크 추가해요!
https://ko.javascript.info/script-async-defer

**Comment by S0YKIM** [comment]
1. 쿼리셀렉터나 클래스를 선언한 파일을 별도의 폴더에 저장해서 관리하니 깔끔하네요!

2. /src/js/index.js:8-11
counters와 currentId 라는 상수를 따로 선언하여 별도로 값을 또 저장할 필요가 없다고 생각해서 다음과 같은 두줄로 짧게 줄여보았는데 정상 작동하네요.
this._counters = JSON.parse(localStorage.getItem('counters'));
this._currentId = Number(localStorage.getItem('id'));

3. /src/js/index.js:12
map 함수를 이용해서 새로운 인스턴스를 생성하고 render 함수를 따로 만들어 렌더링한 것이 보기에 깔끔하고 좋아요.

4. /src/js/index.js:107
closest 메서드를 이용해서 해당하는 카운터 ID를 가져오는 것 너무 좋아요. 문벅스 강의에서 배운 것을 100% 잘 활용하고 계시네요!

5. 이건 디자인 측면의 문제라 뭐가 맞고 틀리다고 할 수 있는건 아니지만 제 생각에는 맨 위에 고정된 카운터에 있는 +1, 0, -1 버튼이랑 아래 추가되는 카운터들에 있는 +1, 0, -1 버튼의 디자인이 통일되면 더 보기 좋을 것 같아요. 코드를 작성 시에도 따로 디자인할 필요 없이 똑같은 class 로 선언하면 더 시간도 절약하실 수 있을 것 같습니다!


코드나 변수명이 한눈에 이해되도록 잘 지어주셨고 그동안 배운 자바스크립트 개념을 정말 잘 활용하셨다는 인상을 받았습니다 :)

**Comment by MichelleJin12** [comment]
1. favicon.ico 추가하기(console에서 에러떠서)
2. counter 추가할 때 id가 0,1,2,3,4,.. 늘어나고 다시 지우고 추가하면 그 뒤의 숫자인 5,6,7,8로 늘어나는데 사라졌을 때 0,1,2,3 다시 시작하게 하면 좋을 것 같다.
3. counter 추가하고 삭제할 때, 다시 정렬되어서 여러 개의 counter가 있을 땐 어떤 counter가 삭제되었는지 알기 힘들다. counter를 추가할 때 어떤식으로든 (번호, 영역) 각각 counter의 위치를 주어서, 어떤 카운터가 삭제, 추가되었는지 알게 하면 좋겠다.

- 이 모든 것들은 사실 제꺼에도 해당됩니닷ㅋㅋㅋㅋㅋ
- 고생하셨어요~~~!!!!!

**Comment by dopamingo** [comment]
1. src/js/modules/Counter.js 
신기하네요 getter 이거 어떻게 쓰는건데 . . . ~! 참고하겠습니다

2. src/js/index.js 
전반적으로 리액트같은 느낌이 드네요 껄껄
:40
이거 왠지 삭제버튼에 쓰일 거 같은데 아닌가요
:67
오호 예외처리를 이런식으로 하는군요

나만 왜 이렇게 짧은 느낌이지 . . .
항상 배울점이 많은 heehkim님 고생많으셨어요!!

**Comment by hhkim0729** [comment]
# 뒤늦은 피드백 정리
모두 피드백 감사드려요~!
스터디 모임에서 같이 이야기 나누긴 했지만, 코드 수정하면서 다시 한번 정리한 코멘트를 남겨봅니다...

## @srngch 
> /src/js/index.js:8, 9 좀 더 명확한 변수명은 어떨까요? (ex: `counters` -> `countersLocalData`) 그럼 10, 11 라인의 삼항연산자 부분도 자연스러운 문장처럼 읽할 듯 합니다.

👉 안 그래도 썼다 지웠다 고민한 이름이었는데 딱 알아보셨군요... 호호 **수정 완료!**

> /src/js/index.js:19 이벤트 리스너에 연결된 모든 곳에서 `update()`가 실행되는데 update 안에서 매번 카운터의 인스턴스들를 새롭게 생성하는 이유가 궁금합니다.

👉 로컬스토리지를 DB로 사용하는 거니까 인스턴스를 통째로 저장하지 않고 데이터가 업데이트되면 가져와서 인스턴스를 생성하는 게 맞다고 생각했습니다~!
(아직 자바스크립트 클래스 사용에 대한 감을 못 잡아서 확신이 없네요 😅)

> /src/js/index.js:40 질문. 아직 안 쓰인 메소드인데 추후 어느 상황에서 쓰이게 되나요?

👉 카운터를 삭제할 때 쓰는 메소드인데 만들어두고 사용하는 걸 깜빡했어요. **수정 완료!**

> /src/js/index.js:58 render() 메소드 저도 고민 많이하다가 매 번 개별 카운터의 dom을 추가/수정/삭제하는 방법으로 짰는데, 리액트 같이 버츄얼돔이 없는 상황에서 매번 모든 카운터를 그려주면 비효율적일 같아요. 하지만 코드에서 잘 읽히고 관리하기 쉬운 장점이 있을 것 같습니다. 이 부분은 같이 얘기 나눠보고 싶어요!

👉 저도 이 부분 고민이 많았고 스터디 때도 이 피드백 받아들여서 코드를 고치겠다고 했는데... 그럼 상태 관리를 하는 이유가 뭐지? 하는 생각이 들어 좀 찾아봤더니 jQuery 시대에는 DOM을 직접 조작하다가 지금은 상태를 기준으로 DOM을 렌더링하는 형태를 많이 쓰게 됐다고 해요. 여기서 발생하는 비효율을 개선하기 위해 React 같은 프레임워크가 탄생했다고 하고요. 
검색하다가 이 [튜토리얼](https://css-tricks.com/build-a-state-management-system-with-vanilla-javascript/)을 찾았는데, 찬찬히 따라해보고 다음번에 적용해볼까 고민해볼게요 🤪

> /src/js/index.js::101 자잘한 거지만... 반복되는 `e.target.classList`를 콜백 함수 초반 부분에서 const에 할당 가능.

👉 구조 분해 문법 열심히 써서 **수정 완료!**
 
> /src/js/index.js::134 html에서 script 태그가 맨 아래 있어서 window.onload가 없어도 동일하게 작동. 저는 js 파일 연결을 head 태그 안에 defer로 추가했는데 자세한건 링크 추가해요! https://ko.javascript.info/script-async-defer

👉 완전히 잊고 있던 `defer`...! **수정 완료!**

---

## @S0YKIM 
> 2. /src/js/index.js:8-11
>    counters와 currentId 라는 상수를 따로 선언하여 별도로 값을 또 저장할 필요가 없다고 생각해서 다음과 같은 두줄로 짧게 줄여보았는데 정상 작동하네요.
>    this._counters = JSON.parse(localStorage.getItem('counters'));
>    this._currentId = Number(localStorage.getItem('id'));

👉 로컬 스토리지에 저장된 데이터가 없을 때 예외 처리를 위한 코드였습니다~!

> 5. 이건 디자인 측면의 문제라 뭐가 맞고 틀리다고 할 수 있는건 아니지만 제 생각에는 맨 위에 고정된 카운터에 있는 +1, 0, -1 버튼이랑 아래 추가되는 카운터들에 있는 +1, 0, -1 버튼의 디자인이 통일되면 더 보기 좋을 것 같아요. 코드를 작성 시에도 따로 디자인할 필요 없이 똑같은 class 로 선언하면 더 시간도 절약하실 수 있을 것 같습니다!

👉 개별 카운터의 버튼과는 다른 역할이라 버튼 디자인도 다르게 해보았답니다 호호

---
## @MichelleJin12 
> 1. favicon.ico 추가하기(console에서 에러떠서)

👉 매번 그냥 지나쳤는데 드디어 함 해봤네요. **수정 완료!**
([여기](https://favicon.io/favicon-generator/)가 직관적이고 만들기 쉬워서 메모 겸 추천!)

> 2. counter 추가할 때 id가 0,1,2,3,4,.. 늘어나고 다시 지우고 추가하면 그 뒤의 숫자인 5,6,7,8로 늘어나는데 사라졌을 때 0,1,2,3 다시 시작하게 하면 좋을 것 같다.

👉 id 값은 고유해야 하기 때문에 이거는 어쩔 수 없는 부분인 걸로~!
대신 clear 버튼 눌렀을 때 `id`를 0으로 초기화는 부분이 있었는데 이것도 맞지 않는 것 같아서 이 코드를 삭제해서 **수정 완료!**

> 3. counter 추가하고 삭제할 때, 다시 정렬되어서 여러 개의 counter가 있을 땐 어떤 counter가 삭제되었는지 알기 힘들다. counter를 추가할 때 어떤식으로든 (번호, 영역) 각각 counter의 위치를 주어서, 어떤 카운터가 삭제, 추가되었는지 알게 하면 좋겠다.

👉 저도 많이 고민한 부분인데 어떻게 해야 할지 아직 적당한 아이디어가 없네요 😥
`id` 값을 노출하는 건 안 될 것 같고, 배경이나 테두리 색을 랜덤으로 해보려고 했더니 그 색을 또 데이터에 저장해야 하고, 인덱스 값을 주면 결국 순서대로 정렬되니까 딱히 구분이 안 되고....
괜찮은 아이디어 떠오르시면 공유해주세요~!

---
## @dopamingo 
> 2. src/js/index.js
>    전반적으로 리액트같은 느낌이 드네요 껄껄

👉 리액트의 망령... 👻

>    :40
>    이거 왠지 삭제버튼에 쓰일 거 같은데 아닌가요

👉 정확히 맞았답니다... **수정 완료!**
